name: Rust

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: |
        sudo apt-get -y install libopencv-dev clang libclang-dev
        pip install git + https://github.com/UCSD-E4E/synology-download.git
        python ./scripts/tests_setup.py
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
